import {
  User,
  Course,
  GradeItem,
  AttendanceRecord,
  Exam,
  StudentSubmission,
  DocumentRequest,
  FinancialTransaction,
  ScheduleEvent,
  PushNotification,
  ChatMessage,
  SupportTicket,
  ERPLog,
  MercadoPagoConfig,
  SofiaSettings,
  IntegrationKeyRecord,
  SystemUpdateManager,
  IntegrationAuditLog,
  SystemModule,
  SecurityAuditReport,
} from '../types';

export const DEFAULT_MASTER_PASSWORD = 'ELOIZIO@MASTER2026';

export const INITIAL_USERS: User[] = [
  {
    id: 'user_ceo_eloizio',
    name: 'Eloizio Silva (CEO)',
    email: 'mecanicoeloizio@gmail.com',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    cpf: '128.***.***-34',
    registrationNumber: 'CEO-2026-0001',
    department: 'Diretoria Geral & Grupo Eloizio',
    phone: '(21) 98764-8727',
    status: 'active',
    password: DEFAULT_MASTER_PASSWORD,
    encryptedDataHash: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b5c4d3e2f1a0b9a8b7c6d5e4f',
  },
  {
    id: 'user_admin_sofia',
    name: 'Sofia Vanguard',
    email: 'sofia@grupoeloizio.com.br',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    cpf: '219.***.***-60',
    registrationNumber: 'VANGUARD-2026-0002',
    department: 'Expert Vanguard em Cursos & Estratégia Educacional',
    phone: '(21) 99613-4073',
    status: 'active',
    password: DEFAULT_MASTER_PASSWORD,
    encryptedDataHash: '8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b5c4d3e2f1a0b9a8b7c6d5e4f9a',
  },
  {
    id: 'user_admin_eloizio_corp',
    name: 'Eloizio Silva (CEO)',
    email: 'eloizio@grupoeloizio.com.br',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    cpf: '128.***.***-34',
    registrationNumber: 'CEO-2026-0001',
    department: 'Diretoria Geral & Grupo Eloizio',
    phone: '(21) 98764-8727',
    status: 'active',
    password: DEFAULT_MASTER_PASSWORD,
    encryptedDataHash: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b5c4d3e2f1a0b9a8b7c6d5e4f',
  },
  {
    id: 'user_teacher_1',
    name: 'Profa. Dra. Mariana Fernandes',
    email: 'mariana.fernandes@grupoeloizio.com.br',
    role: 'teacher',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    registrationNumber: 'DOC-2024-4011',
    department: 'Coordenação Acadêmica de Cursos Livres',
    phone: '(21) 99613-4073',
    status: 'active',
    password: DEFAULT_MASTER_PASSWORD,
    encryptedDataHash: '7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
  },
  {
    id: 'user_student_1',
    name: 'Lucas Silva Prado',
    email: 'aluno@grupoeloizio.com.br',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    cpf: '348.***.***-89',
    registrationNumber: 'MAT-2026-9812',
    courseId: 'course_1',
    phone: '(21) 99999-8888',
    status: 'active',
    password: DEFAULT_MASTER_PASSWORD,
    encryptedDataHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course_1',
    title: 'Engenharia de Software Moderna & Arquitetura Cloud',
    shortDescription: 'Do design de sistemas escaláveis à computação distribuída e integração com Inteligência Artificial.',
    fullDescription: 'Este curso completo de nível superior desenvolve competências sólidas em microsserviços, DevOps, segurança de software, banco de dados distribuídos e automação em nuvem com GCP e AWS. Aulas teóricas e práticas com projetos reais.',
    category: 'Tecnologia',
    price: 1890,
    installments: 12,
    workloadHours: 360,
    level: 'Avançado',
    instructorId: 'user_teacher_1',
    instructorName: 'Profa. Dra. Mariana Fernandes',
    instructorTitle: 'Doutora em Ciência da Computação pela USP',
    thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800',
    featured: true,
    enrolledStudentsCount: 342,
    rating: 4.9,
    tags: ['Arquitetura', 'Cloud', 'TypeScript', 'DevOps', 'Clean Architecture'],
    syllabus: [
      {
        id: 'mod_1',
        title: 'Módulo 1: Fundamentos de Arquitetura de Software',
        description: 'Padrões de projeto, Clean Code e Domain-Driven Design (DDD).',
        lessons: [
          {
            id: 'les_1',
            title: '1. Introdução à Arquitetura Orientada a Eventos',
            description: 'Compreenda a separação de responsabilidades e desacoplamento de serviços assíncronos.',
            durationMinutes: 45,
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
            transcript: 'Olá a todos. Nesta aula vamos aprofundar na transição de sistemas monolíticos para arquiteturas dirigidas por eventos. Veremos conceitos de pub/sub, mensageria e consistência eventual.',
            isCompleted: true,
            downloadableMaterials: [
              { title: 'Guia-Arquitetura-Eventos.pdf', url: '#', size: '2.4 MB' },
              { title: 'Slides-Aula-01.pdf', url: '#', size: '1.1 MB' },
            ],
          },
          {
            id: 'les_2',
            title: '2. Princípios SOLID e Design Patterns Práticos',
            description: 'Implementação real em TypeScript com exemplos em microsserviços.',
            durationMinutes: 52,
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
            transcript: 'Vamos dissecar o Princípio de Inversão de Dependência e Liskov Substitution em projetos corporativos.',
            isCompleted: true,
            downloadableMaterials: [
              { title: 'Exemplos-Codigo-SOLID.zip', url: '#', size: '4.8 MB' },
            ],
          },
          {
            id: 'les_3',
            title: '3. Modelagem de Domínio com DDD e CQRS',
            description: 'Divisão de Bounded Contexts, Aggregates e Projeções de Leitura.',
            durationMinutes: 60,
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
            transcript: 'Aprenda a mapear linguagens ubíquas e construir modelos sem anomias estruturais.',
            isCompleted: false,
            downloadableMaterials: [
              { title: 'Diagrama-Bounded-Contexts.pdf', url: '#', size: '890 KB' },
            ],
          },
        ],
      },
      {
        id: 'mod_2',
        title: 'Módulo 2: Resiliência, Criptografia e Alta Disponibilidade',
        description: 'Circuit breakers, rate limiting, hashing criptográfico e conformidade LGPD.',
        lessons: [
          {
            id: 'les_4',
            title: '4. Criptografia em Trânsito e em Repouso',
            description: 'Uso de chaves AES-GCM, TLS 1.3 e gestão de segredos em nuvem.',
            durationMinutes: 48,
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
            transcript: 'Garantir a integridade dos dados requer cifras modernas e práticas rigorosas de proteção a dados sensíveis.',
            isCompleted: false,
          },
          {
            id: 'les_5',
            title: '5. Observabilidade: Métricas, Tracing e Logs Distribuídos',
            description: 'OpenTelemetry, Prometheus e análise de gargalos em microsserviços.',
            durationMinutes: 55,
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
            transcript: 'Se você não mede, você não controla. Vamos ver como rastrear requisições distribuídas.',
            isCompleted: false,
          },
        ],
      },
    ],
  },
  {
    id: 'course_2',
    title: 'Gestão Escolar 360°, Liderança & Finanças Educacionais',
    shortDescription: 'Estratégias de expansão pedagógica, compliance regulatório e gestão financeira sustentável.',
    fullDescription: 'Curso intensivo para gestores, diretores, coordenadores e líderes de instituições de ensino. Abrange precificação de mensalidades, retenção de matrículas, automação acadêmica e relatórios gerenciais.',
    category: 'Negócios',
    price: 1450,
    installments: 12,
    workloadHours: 240,
    level: 'Intermediário',
    instructorId: 'user_admin_1',
    instructorName: 'Prof. Me. Carlos Mendes',
    instructorTitle: 'Especialista em Gestão Estratégica e Finanças Corporativas',
    thumbnail: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&q=80&w=800',
    featured: true,
    enrolledStudentsCount: 215,
    rating: 4.8,
    tags: ['Liderança', 'Finanças', 'Gestão Escolar', 'ERP', 'Planejamento'],
    syllabus: [
      {
        id: 'mod_2_1',
        title: 'Módulo 1: Planejamento Orçamentário e Redução de Inadimplência',
        description: 'Táticas para cobrança amigável, gateway de pagamento e fluxo de caixa.',
        lessons: [
          {
            id: 'les_2_1',
            title: '1. Estruturação do Fluxo de Caixa Escolar',
            description: 'Equilibrando receitas sazonais de matrículas com custos fixos anuais.',
            durationMinutes: 40,
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
            transcript: 'A sustentabilidade de uma escola depende de previsibilidade de receitas e controle rigoroso de custos.',
            isCompleted: false,
          },
        ],
      },
    ],
  },
  {
    id: 'course_3',
    title: 'UI/UX Design de Produtos Digitais & Design Systems',
    shortDescription: 'Criação de interfaces acessíveis, prototipagem avançada em Figma e componentes em escala.',
    fullDescription: 'Domine pesquisas qualitativas de usuários, testes de usabilidade, heurísticas de Nielsen e a construção de Design Systems robustos para aplicações Web e Mobile.',
    category: 'Design',
    price: 1290,
    installments: 10,
    workloadHours: 180,
    level: 'Iniciante',
    instructorId: 'user_teacher_1',
    instructorName: 'Profa. Dra. Mariana Fernandes',
    instructorTitle: 'Designer & Pesquisadora em IHC',
    thumbnail: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&q=80&w=800',
    featured: false,
    enrolledStudentsCount: 189,
    rating: 4.95,
    tags: ['Figma', 'UI Design', 'Design System', 'Acessibilidade'],
    syllabus: [],
  },
  {
    id: 'course_4',
    title: 'Inteligência Artificial Aplicada & Machine Learning',
    shortDescription: 'Modelos preditivos, redes neurais profundas, visão computacional e LLMs aplicados a negócios.',
    fullDescription: 'Aprenda Python científico, PyTorch, TensorFlow e como orquestrar modelos generativos com grounding em APIs corporativas.',
    category: 'Tecnologia',
    price: 2190,
    installments: 12,
    workloadHours: 420,
    level: 'Avançado',
    instructorId: 'user_teacher_1',
    instructorName: 'Profa. Dra. Mariana Fernandes',
    instructorTitle: 'Cientista de Dados e Pesquisadora de IA',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800',
    featured: true,
    enrolledStudentsCount: 410,
    rating: 4.92,
    tags: ['Machine Learning', 'Python', 'LLMs', 'Redes Neurais'],
    syllabus: [],
  },
];

export const INITIAL_GRADES: GradeItem[] = [
  {
    id: 'grd_1',
    studentId: 'user_student_1',
    courseId: 'course_1',
    subject: 'Arquitetura de Microsserviços & Cloud',
    p1: 9.5,
    p2: 8.8,
    assignment: 10.0,
    average: 9.4,
    status: 'Aprovado',
  },
  {
    id: 'grd_2',
    studentId: 'user_student_1',
    courseId: 'course_1',
    subject: 'Segurança da Informação e Criptografia',
    p1: 8.5,
    p2: 9.0,
    assignment: 8.5,
    average: 8.7,
    status: 'Aprovado',
  },
  {
    id: 'grd_3',
    studentId: 'user_student_1',
    courseId: 'course_1',
    subject: 'DevOps & Integração Contínua (CI/CD)',
    p1: 7.0,
    p2: 8.0,
    assignment: 9.0,
    average: 7.9,
    status: 'Aprovado',
  },
  {
    id: 'grd_4',
    studentId: 'user_student_1',
    courseId: 'course_1',
    subject: 'Bancos de Dados Distribuídos e NoSQL',
    p1: 8.0,
    p2: 0,
    assignment: 8.5,
    average: 5.5,
    status: 'Em Andamento',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  { id: 'att_1', studentId: 'user_student_1', date: '2026-09-22', subject: 'Arquitetura de Microsserviços', status: 'present', verifiedCode: 'PRES-9912' },
  { id: 'att_2', studentId: 'user_student_1', date: '2026-09-24', subject: 'Segurança da Informação', status: 'present', verifiedCode: 'PRES-4421' },
  { id: 'att_3', studentId: 'user_student_1', date: '2026-09-26', subject: 'DevOps & CI/CD', status: 'present', verifiedCode: 'PRES-1102' },
  { id: 'att_4', studentId: 'user_student_1', date: '2026-09-28', subject: 'Bancos de Dados Distribuídos', status: 'present', verifiedCode: 'PRES-7788' },
  { id: 'att_5', studentId: 'user_student_1', date: '2026-09-18', subject: 'Segurança da Informação', status: 'justified', verifiedCode: 'JUST-MED-01' },
];

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam_1',
    courseId: 'course_1',
    title: 'Quiz de Fixação: Padrões de Projeto & SOLID',
    description: 'Teste seus conhecimentos sobre inversão de dependência, single responsibility e segregação de interfaces.',
    type: 'quiz',
    dueDate: '2026-10-15',
    durationMinutes: 20,
    totalPoints: 10,
    questions: [
      {
        id: 'q1',
        question: 'No princípio SOLID, o que dita o "O" (Open/Closed Principle)?',
        options: [
          'Entidades de software devem ser abertas para extensão, mas fechadas para modificação.',
          'Um arquivo deve conter apenas uma classe e uma função.',
          'As classes devem ser abertas para edição em tempo de execução.',
          'Nenhuma classe pode estender de outra classe abstrata.',
        ],
        correctOptionIndex: 0,
        explanation: 'O Princípio Aberto/Fechado estabelece que novas funcionalidades devem ser adicionadas sem alterar o código já testado e consolidado.',
      },
      {
        id: 'q2',
        question: 'Qual a principal vantagem da Inversão de Dependência (Dependency Inversion)?',
        options: [
          'Acelerar a velocidade de carregamento de páginas web.',
          'Módulos de alto nível não devem depender de módulos de baixo nível; ambos devem depender de abstrações.',
          'Substituir bancos de dados relacionais por arquivos JSON.',
          'Evitar o uso de testes unitários.',
        ],
        correctOptionIndex: 1,
        explanation: 'A Inversão de Dependência permite desacoplar a regra de negócio da infraestrutura técnica (banco, gateways, etc).',
      },
      {
        id: 'q3',
        question: 'Em arquitetura dirigida por eventos, qual componente é responsável por receber mensagens e redistribuí-las aos assinantes?',
        options: [
          'Event Broker / Mensageria (ex: Kafka, RabbitMQ)',
          'Firewall de Rede',
          'Navegador Web do cliente',
          'Tabela temporária no banco',
        ],
        correctOptionIndex: 0,
        explanation: 'O Message Broker garante entrega confiável e assíncrona entre produtores e consumidores de eventos.',
      },
    ],
  },
  {
    id: 'exam_2',
    courseId: 'course_1',
    title: 'Trabalho Prático: Projeto de Microsserviço com Gateway',
    description: 'Desenvolver a documentação arquitetural e o repositório de um microsserviço de pagamentos desacoplado.',
    type: 'assignment',
    dueDate: '2026-10-30',
    durationMinutes: 0,
    totalPoints: 10,
    instructions: 'Envie um arquivo PDF com o diagrama arquitetural C4 Model e o link para o repositório Git com os testes integrados.',
  },
];

export const INITIAL_SUBMISSIONS: StudentSubmission[] = [
  {
    id: 'sub_1',
    examId: 'exam_1',
    studentId: 'user_student_1',
    studentName: 'Lucas Silva Prado',
    submittedAt: '2026-09-25T14:30:00Z',
    score: 10,
    status: 'graded',
    answers: [
      { questionId: 'q1', selectedOption: 0 },
      { questionId: 'q2', selectedOption: 1 },
      { questionId: 'q3', selectedOption: 0 },
    ],
    teacherFeedback: 'Excelente aproveitamento! Demonstrou domínio total dos princípios arquiteturais.',
  },
];

export const INITIAL_DOCUMENTS: DocumentRequest[] = [
  {
    id: 'doc_req_1',
    studentId: 'user_student_1',
    studentName: 'Lucas Silva Prado',
    documentType: 'carteirinha',
    title: 'Carteirinha Estudantil Digital Oficial (Padrão DNE)',
    feeAmount: 25.0,
    paymentStatus: 'paid',
    paymentMethod: 'pix',
    mercadoPagoPaymentId: 'MP-892189412',
    requestedAt: '2026-09-20T10:15:00Z',
    issuedAt: '2026-09-20T10:16:02Z',
    validationHash: 'DNE-2026-BR-998812A7C',
  },
];

export const INITIAL_TRANSACTIONS: FinancialTransaction[] = [
  {
    id: 'tx_1',
    type: 'tuition',
    description: 'Mensalidade Setembro/2026 - Eng. Software',
    amount: 157.50,
    studentId: 'user_student_1',
    studentName: 'Lucas Silva Prado',
    date: '2026-09-05',
    dueDate: '2026-09-10',
    status: 'paid',
    paymentMethod: 'pix',
    mercadoPagoReference: 'MP-PIX-998231',
  },
  {
    id: 'tx_2',
    type: 'tuition',
    description: 'Mensalidade Outubro/2026 - Eng. Software',
    amount: 157.50,
    studentId: 'user_student_1',
    studentName: 'Lucas Silva Prado',
    date: '2026-09-28',
    dueDate: '2026-10-10',
    status: 'pending',
    paymentMethod: 'boleto',
    mercadoPagoReference: 'MP-BOL-104928',
  },
  {
    id: 'tx_3',
    type: 'document_fee',
    description: 'Taxa de Emissão: Carteirinha Estudantil Digital',
    amount: 25.00,
    studentId: 'user_student_1',
    studentName: 'Lucas Silva Prado',
    date: '2026-09-20',
    dueDate: '2026-09-20',
    status: 'paid',
    paymentMethod: 'pix',
    mercadoPagoReference: 'MP-PIX-892189',
  },
  {
    id: 'tx_4',
    type: 'tuition',
    description: 'Mensalidade Setembro/2026 - Aluno Rafael Souza',
    amount: 189.00,
    studentId: 'user_student_2',
    studentName: 'Rafael Souza Castro',
    date: '2026-09-01',
    dueDate: '2026-09-10',
    status: 'overdue',
    paymentMethod: 'boleto',
    mercadoPagoReference: 'MP-BOL-882190',
  },
];

export const INITIAL_SCHEDULE: ScheduleEvent[] = [
  {
    id: 'sch_1',
    courseId: 'course_1',
    dayOfWeek: 'Segunda',
    startTime: '19:00',
    endTime: '21:30',
    subject: 'Arquitetura de Microsserviços & Cloud',
    teacherName: 'Profa. Dra. Mariana Fernandes',
    roomOrLink: 'Sala Virtual Ao Vivo 01 & Auditório A',
  },
  {
    id: 'sch_2',
    courseId: 'course_1',
    dayOfWeek: 'Quarta',
    startTime: '19:00',
    endTime: '21:30',
    subject: 'Segurança da Informação e Criptografia',
    teacherName: 'Profa. Dra. Mariana Fernandes',
    roomOrLink: 'Laboratório de Redes & Meet',
    hasChanged: true,
    changeNotice: 'Alteração: A aula foi antecipada para as 18h45 com laboratório prático de chaves!',
  },
  {
    id: 'sch_3',
    courseId: 'course_1',
    dayOfWeek: 'Sexta',
    startTime: '19:00',
    endTime: '21:30',
    subject: 'DevOps, CI/CD & Containers',
    teacherName: 'Prof. Convidado Felipe Castro',
    roomOrLink: 'Sala Virtual Ao Vivo 03',
  },
];

export const INITIAL_NOTIFICATIONS: PushNotification[] = [
  {
    id: 'notif_1',
    title: 'Aviso de Mudança na Grade Horária',
    message: 'A aula de Segurança da Informação nesta quarta-feira iniciará 15 minutos mais cedo com laboratório prático.',
    targetRole: 'student',
    category: 'schedule',
    timestamp: 'Hoje, 08:15',
    read: false,
  },
  {
    id: 'notif_2',
    title: 'Nota Lançada: Prova 1',
    message: 'A nota da P1 de Arquitetura de Microsserviços foi publicada no seu Boletim Digital. Nota: 9.5!',
    targetRole: 'student',
    category: 'grade',
    timestamp: 'Ontem, 16:40',
    read: false,
  },
  {
    id: 'notif_3',
    title: 'Carteirinha Estudantil Emitida',
    message: 'O pagamento via Mercado Pago foi confirmado. Sua carteirinha já pode ser impressa ou baixada.',
    targetRole: 'student',
    category: 'payment',
    timestamp: '20 de Setembro',
    read: true,
  },
  {
    id: 'notif_4',
    title: 'Nova matrícula realizada',
    message: 'Novo aluno matriculado no curso Engenharia de Software Moderna via Vitrine.',
    targetRole: 'teacher',
    category: 'academic',
    timestamp: 'Hoje, 07:30',
    read: false,
  },
];

export const INITIAL_CHAT: ChatMessage[] = [
  {
    id: 'msg_1',
    senderId: 'user_teacher_1',
    senderName: 'Profa. Dra. Mariana Fernandes',
    senderRole: 'teacher',
    senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    courseId: 'course_1',
    content: 'Olá a todos da turma de Engenharia de Software! O material complementar da aula de Arquitetura Limpa já está disponível para download.',
    timestamp: '09:00',
  },
  {
    id: 'msg_2',
    senderId: 'user_student_1',
    senderName: 'Lucas Silva Prado',
    senderRole: 'student',
    senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    courseId: 'course_1',
    content: 'Bom dia professora Mariana! Gostaria de tirar uma dúvida sobre o trabalho prático: o diagrama deve seguir a notação C4?',
    timestamp: '09:12',
  },
  {
    id: 'msg_3',
    senderId: 'user_teacher_1',
    senderName: 'Profa. Dra. Mariana Fernandes',
    senderRole: 'teacher',
    senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    courseId: 'course_1',
    content: 'Sim, Lucas! Recomendo os níveis 1 (Context) e 2 (Containers). Ficará excelente!',
    timestamp: '09:15',
  },
];

export const INITIAL_ERP_LOGS: ERPLog[] = [
  {
    id: 'erp_1',
    system: 'TOTVS Edu',
    action: 'Sincronização de Matrículas e Contratos',
    entity: 'Matrícula',
    status: 'success',
    timestamp: '2026-09-29 08:00:21',
    payloadHash: '7c992a10b48...912a',
  },
  {
    id: 'erp_2',
    system: 'Senior Sponte',
    action: 'Envio de Fechamento Contábil e Boletos Mercado Pago',
    entity: 'Financeiro',
    status: 'success',
    timestamp: '2026-09-29 07:30:15',
    payloadHash: '4a112f9801c...cc01',
  },
  {
    id: 'erp_3',
    system: 'SAP Education',
    action: 'Exportação de Diário de Classe e Frequências',
    entity: 'Frequência',
    status: 'success',
    timestamp: '2026-09-28 23:15:00',
    payloadHash: '99bca88172d...ee45',
  },
];

export const INITIAL_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 'tkt_1',
    userId: 'user_student_1',
    userName: 'Lucas Silva Prado',
    userRole: 'student',
    category: 'secretaria',
    subject: 'Solicitação de 2ª via de Histórico Escolar com Carimbo Digital',
    description: 'Preciso do histórico carimbado para apresentar no processo seletivo de pós-graduação.',
    status: 'resolvido',
    priority: 'alta',
    createdAt: '2026-09-22 11:00',
    messages: [
      { sender: 'Lucas Silva Prado', text: 'Boa tarde, realizei o pagamento da taxa e preciso do documento em PDF.', time: '11:00' },
      { sender: 'Secretaria Acadêmica', text: 'Olá Lucas! Seu documento foi validado e assinado com certificado ICP-Brasil. Já está disponível na aba de Documentos.', time: '14:20' },
    ],
  },
];

export const INITIAL_LIBRARY: import('../types').LibraryItem[] = [
  {
    id: 'lib_1',
    title: 'Manual de Engenharia de Software Moderna & Microsserviços',
    author: 'Profa. Dra. Mariana Fernandes',
    category: 'Livro',
    description: 'Compêndio oficial do curso cobrindo Clean Architecture, DDD, Event-Driven Architecture e microsserviços escaláveis.',
    fileSize: '14.8 MB',
    format: 'PDF',
    downloadUrl: '#',
    readOnlineAvailable: true,
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'lib_2',
    title: 'Guia de Diretrizes LGPD & Segurança de Dados em Nuvem',
    author: 'Comissão de Governança Digital EduVanguard',
    category: 'Apostila',
    description: 'Normas de criptografia aplicada, controle de acesso RBAC e auditoria de sistemas escolares.',
    fileSize: '4.2 MB',
    format: 'PDF',
    downloadUrl: '#',
    readOnlineAvailable: true,
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'lib_3',
    title: 'Artigo: Padrões Resilientes em Nuvem e Circuit Breakers',
    author: 'Depto. de Pesquisa e Extensão em Computação',
    category: 'Paper Científico',
    description: 'Estudo comparativo de tolerância a falhas em sistemas de alto volume transacional.',
    fileSize: '1.9 MB',
    format: 'PDF',
    downloadUrl: '#',
    readOnlineAvailable: true,
    coverImage: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'lib_4',
    title: 'Gestão Escolar e Liderança Pedagógica Contemporânea',
    author: 'Prof. Me. Carlos Alberto Mendes',
    category: 'Livro',
    description: 'Fundamentos de governança educacional, planejamento estratégico e retenção de alunos.',
    fileSize: '8.7 MB',
    format: 'PDF',
    downloadUrl: '#',
    readOnlineAvailable: true,
    coverImage: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=400',
  },
];

export const INITIAL_ACADEMIC_EVENTS: import('../types').AcademicEvent[] = [
  {
    id: 'evt_1',
    title: 'Semana de Avaliações Oficiais P1',
    type: 'prova',
    date: '2026-10-14',
    endDate: '2026-10-21',
    description: 'Período oficial para aplicação das Provas P1 em todas as disciplinas do semestre letivo.',
    targetRole: 'all',
  },
  {
    id: 'evt_2',
    title: 'Prazo Limite: Entrega de Trabalhos Interdisciplinares T1',
    type: 'trabalho',
    date: '2026-10-30',
    description: 'Envio digital dos arquivos PDF e links de repositórios pelos alunos no portal.',
    targetRole: 'student',
  },
  {
    id: 'evt_3',
    title: 'Reunião Geral de Planejamento Pedagógico & NDE',
    type: 'reuniao',
    date: '2026-11-05',
    description: 'Alinhamento do corpo docente com a coordenação e diretoria acadêmica.',
    targetRole: 'teacher',
  },
  {
    id: 'evt_4',
    title: 'Fechamento de Notas e Frequências do 3º Bimestre',
    type: 'evento',
    date: '2026-11-20',
    description: 'Lançamento de médias no sistema para sincronização automática com o ERP acadêmico.',
    targetRole: 'teacher',
  },
  {
    id: 'evt_5',
    title: 'Abertura do Vestibular e Matrículas 2027/1 na Vitrine',
    type: 'vestibular',
    date: '2026-12-01',
    endDate: '2027-01-30',
    description: 'Início da campanha de captação de novos alunos com desconto via Mercado Pago.',
    targetRole: 'all',
  },
];

export const INITIAL_LEADS: import('../types').MarketingLead[] = [
  {
    id: 'lead_1',
    name: 'Carolina Mendes Ribeiro',
    email: 'carolina.ribeiro@email.com',
    phone: '(11) 98112-3344',
    courseInterest: 'Engenharia de Software Moderna & Arquitetura Cloud',
    status: 'proposta_enviada',
    notes: 'Interessada na formação para transição de carreira. Cupom SOFIA15 aplicado.',
    createdAt: '2026-09-29 08:10',
    source: 'chat_sofia',
    proposalCode: 'PROP-SOFIA-8821',
    discountPercentage: 15,
  },
  {
    id: 'lead_2',
    name: 'Thiago Faria Albuquerque',
    email: 'thiago.albuquerque@empresa.com.br',
    phone: '(19) 99778-5522',
    courseInterest: 'Gestão Escolar 360°, Liderança & Finanças',
    status: 'novo',
    notes: 'Diretor de colégio particular buscando capacitação para sua equipe de coordenadores.',
    createdAt: '2026-09-28 17:35',
    source: 'whatsapp',
  },
];

// Cryptography & Security helper

export const DEFAULT_MERCADOPAGO_CONFIG: MercadoPagoConfig = {
  publicKey: 'APP_USR-9a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d',
  accessToken: 'APP_USR-7281928374659102-092916-d8f92a1b3c4e5f6a7b8c9d0e1f2a3b4c-192837465',
  clientId: 'GRUPO-ELOIZIO-PROD',
  clientSecret: 'sec_mp_live_grupoeloizio_2026',
  webhookUrl: 'https://grupoeloizio.com.br/api/mercadopago/webhook',
  webhookSecret: 'whsec_mp_grupoeloizio_live_secret',
  environment: 'production',
  autoApproveSimulation: false,
  pixDiscountPercent: 15,
  maxInstallments: 12,
  notificationEmail: 'financeiro@grupoeloizio.com.br',
  lastTestedAt: '2026-10-05 17:00',
  connectionStatus: 'connected',
};

export const DEFAULT_SOFIA_SETTINGS: SofiaSettings = {
  name: 'Sofia Vanguard',
  title: 'Expert Vanguard em Cursos & Estrategista de Marketing',
  personality: 'comercial',
  romanticToneLevel: 'moderada',
  activeCoupon: 'SOFIA15',
  discountPercentage: 15,
  whatsappNumber: '21996134073',
  welcomeMessage: '✨ Olá! Eu sou a Sofia, a Expert Vanguard do Grupo Eloizio. Estou aqui para entender seus objetivos de carreira e te guiar rumo à melhor formação prática com certificação oficial MEC. Qual área você deseja transformar hoje?',
  enablePoeticQuotes: false,
  enableDirectCheckoutAction: true,
};

export const DEFAULT_INTEGRATION_KEYS: IntegrationKeyRecord[] = [
  {
    id: 'int_mp_1',
    name: 'Mercado Pago Checkout & PIX Transparente',
    category: 'payment',
    service: 'mercadopago',
    primaryToken: 'APP_USR-7281928374659102-092916-d8f92a1b3c4e5f6a7b8c9d0e1f2a3b4c-192837465',
    secondaryKey: 'APP_USR-9a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d',
    secretKey: 'whsec_mp_live_grupoeloizio_2026',
    endpointUrl: 'https://api.mercadopago.com/v1',
    environment: 'production',
    status: 'active',
    lastPingAt: '2026-10-05 17:00',
    autoSync: true,
    notes: 'Processamento exclusivo de matrículas, mensalidades e taxas com conciliação via Webhook em Produção.',
    createdAt: '2026-09-29 10:00',
    updatedAt: '2026-10-05 17:00',
    webhookEvents: ['payment.created', 'payment.updated', 'payment.approved'],
  },
  {
    id: 'int_wpp_1',
    name: 'WhatsApp Business API (Sofia Vanguard & Grupo Eloizio)',
    category: 'communication',
    service: 'whatsapp_official',
    primaryToken: 'wpp_live_tok_99182374619283746591',
    secondaryKey: '21996134073',
    secretKey: 'whsec_wpp_sofia_secret_2026',
    endpointUrl: 'https://api.whatsapp.com/v18.0/messages',
    environment: 'production',
    status: 'active',
    lastPingAt: '2026-10-02 15:42',
    autoSync: true,
    notes: 'Linha oficial Grupo Eloizio (21 996134073) com atendimento inteligente de Sofia Vanguard e suporte do CEO Eloizio (21 987648727).',
    createdAt: '2026-09-29 10:00',
    updatedAt: '2026-10-02 15:42',
    webhookEvents: ['messages.received', 'messages.delivered', 'lead.captured'],
  },
  {
    id: 'int_gemini_1',
    name: 'Google Gemini 3.1 Pro & Inteligência Multimodal',
    category: 'ai',
    service: 'gemini_ai',
    primaryToken: 'AIzaSyB_server_side_key_vault_active',
    endpointUrl: 'https://generativelanguage.googleapis.com',
    environment: 'production',
    status: 'active',
    lastPingAt: '2026-10-02 15:44',
    autoSync: true,
    notes: 'Motor cognitivo com alta sensibilidade poética, conhecimento integral das ementas e diagnóstico de peças e máquinas.',
    createdAt: '2026-09-29 10:00',
    updatedAt: '2026-10-02 15:44',
  },
  {
    id: 'int_totvs_1',
    name: 'TOTVS Protheus / ERP Contábil & Fiscal',
    category: 'erp',
    service: 'erp_totvs',
    primaryToken: 'totvs_bearer_token_771928_elz',
    secondaryKey: 'EMP-GRUPO-ELOIZIO-001',
    secretKey: 'totvs_client_secret_9941',
    endpointUrl: 'https://totvs.grupoeloizio.com.br/api/financeiro/v1',
    environment: 'production',
    status: 'active',
    lastPingAt: '2026-10-02 14:15',
    autoSync: true,
    notes: 'Exportação e reconciliação contábil 100% online de notas de serviço e receitas de cursos.',
    createdAt: '2026-09-29 10:00',
    updatedAt: '2026-10-02 14:15',
  },
  {
    id: 'int_mec_1',
    name: 'SISTEC / MEC & Chave Criptográfica ICP-Edu',
    category: 'government',
    service: 'sistec_mec',
    primaryToken: 'ICP-EDU-PKI-BR-99281-OK',
    secondaryKey: 'CERT-MEC-LDB-9394-REG',
    endpointUrl: 'https://sistec.mec.gov.br/ws/certificados/v2',
    environment: 'production',
    status: 'active',
    lastPingAt: '2026-10-02 13:00',
    autoSync: true,
    notes: 'Validação e carimbo no Livro de Registro da Secretaria Geral com amparo legal Art. 42 LDB.',
    createdAt: '2026-09-29 10:00',
    updatedAt: '2026-10-02 13:00',
  },
  {
    id: 'int_whk_1',
    name: 'Hub de Webhooks Externos (Eventos & Atualizações)',
    category: 'webhook',
    service: 'custom_webhook',
    primaryToken: 'whk_stream_key_994821',
    secretKey: 'whk_hmac_secret_eloizio_2026',
    endpointUrl: 'https://grupoeloizio.com.br/api/v1/event-stream',
    environment: 'production',
    status: 'active',
    lastPingAt: '2026-10-02 15:40',
    autoSync: true,
    notes: 'Disparo de webhooks para CRMs, automação de e-mail e sistemas parceiros a cada matrícula ou certificação.',
    createdAt: '2026-09-29 10:00',
    updatedAt: '2026-10-02 15:40',
    webhookEvents: ['matricula.aprovada', 'certificado.emitido', 'aluno.concluiu_curso'],
  },
];

export const DEFAULT_SYSTEM_UPDATE_MANAGER: SystemUpdateManager = {
  currentVersion: 'v2.5.0 - Enterprise Multi-Module',
  releaseChannel: 'stable',
  autoCheckUpdates: true,
  lastCheckDate: '2026-10-02 15:45',
  availableUpdate: {
    version: 'v2.6.0 - Hub Automação Contábil & IA Multimodal',
    title: 'Atualização do Motor de Diagnóstico por Imagem e Conciliação Automática',
    releaseDate: '2026-10-05',
    severity: 'feature',
    downloadSize: '4.2 MB',
    changelog: [
      'Pipeline de recebimento de fotos de máquinas e peças mecânicas para pré-diagnóstico instantâneo via IA',
      'Conciliação contábil automática de todos os recebimentos via Mercado Pago com emissão de relatórios em 1 clique',
      'Aprimoramento do módulo de certificados digitais com carimbo do tempo criptográfico ICP-Brasil',
      'Central unificada de tokens de integração com monitoramento de latência e rotatividade de segredos',
      'Backups automáticos antes de cada migração estrutural com restauração segura',
    ],
    databaseMigrations: [
      '16_add_multimedia_diagnostics_table.sql',
      '17_add_reconciliation_indexes.sql',
      '18_add_integration_tokens_vault.sql',
    ],
  },
  backupSnapshotCount: 3,
  lastBackupDate: '2026-10-01 23:00',
  autoBackupBeforeUpdate: true,
  updateHistory: [
    {
      id: 'upd_2',
      version: 'v2.5.0',
      appliedAt: '2026-09-29 16:30',
      appliedBy: 'Administrador (Carlos Alberto / Eloizio)',
      status: 'success',
      description: 'Implementação da API Mercado Pago oficial, central de auditoria e simulador acadêmico.',
      migrationsApplied: ['14_mercadopago_webhooks.sql', '15_certificate_validations.sql'],
    },
    {
      id: 'upd_1',
      version: 'v2.4.0',
      appliedAt: '2026-09-15 10:00',
      appliedBy: 'Sistema Base',
      status: 'success',
      description: 'Lançamento do Portal do Aluno com reprodutor de vídeo, apostilas e certificados com Frente e Verso.',
      migrationsApplied: ['01_initial_schema.sql', '02_documents_tables.sql'],
    },
  ],
};

export const DEFAULT_INTEGRATION_LOGS: IntegrationAuditLog[] = [
  {
    id: 'log_1',
    timestamp: '2026-10-02 15:44:12',
    service: 'mercadopago',
    action: 'test_connection',
    status: 'success',
    payloadSummary: 'Credenciais homologadas no ambiente sandbox. Métodos ativos: PIX, Cartão (12x), Boleto.',
    latencyMs: 142,
    ipAddress: '177.18.29.102',
  },
  {
    id: 'log_2',
    timestamp: '2026-10-02 15:42:08',
    service: 'whatsapp_official',
    action: 'health_check',
    status: 'success',
    payloadSummary: 'Instância Sofia Vanguard (21 996134073) conectada com sucesso ao gateway.',
    latencyMs: 89,
    ipAddress: '177.18.29.102',
  },
  {
    id: 'log_3',
    timestamp: '2026-10-02 15:40:22',
    service: 'custom_webhook',
    action: 'event_dispatch',
    status: 'success',
    payloadSummary: 'Webhook disparado para https://grupoeloizio.com.br/api/v1/event-stream (HTTP 200 OK).',
    latencyMs: 115,
    ipAddress: '177.18.29.102',
  },
];

export const DEFAULT_SYSTEM_MODULES: SystemModule[] = [
  {
    id: 'mod_core',
    slug: 'core_security_auth',
    name: 'Núcleo do Sistema & Gestão de Acessos (Auth & RBAC)',
    description: 'Controle central de permissões, criptografia de senhas, sessões e proteção contra força bruta.',
    version: '2.5.0',
    category: 'core',
    enabled: true,
    isCore: true,
    dependencies: [],
    installedAt: '2026-09-01 08:00',
    updatedAt: '2026-10-05 15:00',
    status: 'healthy',
    author: 'Engenharia Central / Grupo Eloizio',
    changelog: ['Implementada proteção contra força bruta', 'Sessões com auto-bloqueio para administradores'],
    features: ['Login multi-perfil (Aluno/Professor/Admin)', 'RBAC Granular', 'Rate-limiting de autenticação'],
  },
  {
    id: 'mod_mercadopago',
    slug: 'mercadopago_gateway',
    name: 'Gateway Mercado Pago Oficial & Conciliação PIX',
    description: 'Processamento exclusivo de cobranças, links de pagamento, PIX instantâneo, cartões e boletos.',
    version: '2.4.2',
    category: 'finance',
    enabled: true,
    isCore: true,
    dependencies: ['mod_core'],
    installedAt: '2026-09-20 10:00',
    updatedAt: '2026-10-02 15:30',
    status: 'healthy',
    author: 'Mercado Pago SDK Integration Team',
    changelog: ['Validação de chave em tempo real', 'Webhooks com verificação HMAC'],
    features: ['PIX com QR Code dinâmico', 'Parcelamento em até 12x', 'Boletos registrados', 'Reconciliação contábil'],
  },
  {
    id: 'mod_cursos',
    slug: 'cursos_online_sala_virtual',
    name: 'Cursos Livres 100% Online & Player com Velocidade',
    description: 'Plataforma de ensino a distância com videoaulas HD, apostilas em PDF, dúvidas e fórum.',
    version: '2.3.0',
    category: 'academic',
    enabled: true,
    isCore: false,
    dependencies: ['mod_core'],
    installedAt: '2026-09-10 12:00',
    updatedAt: '2026-09-29 16:00',
    status: 'healthy',
    author: 'Equipe Pedagógica EduVanguard',
    changelog: ['Adicionado controle de velocidade do player (0.75x a 2x)', 'Download de apostilas por aula'],
    features: ['Videoaulas com controle de playback', 'Apostilas em PDF', 'Plantão de dúvidas com tutores'],
  },
  {
    id: 'mod_certificados',
    slug: 'certificados_mec_icpedu',
    name: 'Certificação Digital com Registro MEC & Chave ICP-Edu',
    description: 'Emissão oficial de certificados com Frente e Verso, ementa, notas e validação pública anti-fraude.',
    version: '2.1.0',
    category: 'academic',
    enabled: true,
    isCore: false,
    dependencies: ['mod_cursos'],
    installedAt: '2026-09-22 14:00',
    updatedAt: '2026-10-01 10:00',
    status: 'healthy',
    author: 'Secretaria Acadêmica & Jurídico',
    changelog: ['Amparo legal impresso Art. 42 LDB', 'Registro oficial no Livro da Secretaria Geral'],
    features: ['Certificado com Frente e Verso', 'QR Code de validação pública', 'Hash SHA-256 ICP-Edu'],
  },
  {
    id: 'mod_sofia_ai',
    slug: 'sofia_vanguard_ai_assistant',
    name: 'Sofia Vanguard — Expert em Cursos & Psicologia de Marketing',
    description: 'Expert Vanguard em Cursos, Carreiras, Psicologia de Marketing Educacional e diagnóstico multimodal.',
    version: '3.1.0',
    category: 'communication',
    enabled: true,
    isCore: false,
    dependencies: ['mod_core'],
    installedAt: '2026-09-25 09:00',
    updatedAt: '2026-10-05 14:30',
    status: 'healthy',
    author: 'Grupo Eloizio AI Lab',
    changelog: ['Identidade 100% Sofia Vanguard (Camilla desconectada)', 'Psicologia de marketing educacional e domínio total dos cursos'],
    features: ['Domínio completo de todos os cursos', 'Psicologia de marketing e conversão', 'Diagnóstico técnico de máquinas'],
  },
  {
    id: 'mod_contabilidade',
    slug: 'contabilidade_assessoria_online',
    name: 'Contabilidade e Assessoria 100% Online',
    description: 'Módulo de consultoria, MEI, declarações e assessoria prática digital sem burocracia.',
    version: '1.8.0',
    category: 'business',
    enabled: true,
    isCore: false,
    dependencies: ['mod_mercadopago'],
    installedAt: '2026-09-28 11:00',
    updatedAt: '2026-10-02 11:00',
    status: 'healthy',
    author: 'Assessoria Contábil Grupo Eloizio',
    changelog: ['Planos mensais e avulsos integrados com Mercado Pago'],
    features: ['Gestão fiscal e MEI', 'Emissão de notas de serviço', 'Atendimento 100% online'],
  },
  {
    id: 'mod_maquinas',
    slug: 'maquinas_costura_mecanica',
    name: 'Oficina Mecânica & Máquinas de Costura (São Gonçalo - RJ)',
    description: 'Compra, venda, conserto, reforma de máquinas industriais e domésticas com suporte a técnicos.',
    version: '1.5.0',
    category: 'business',
    enabled: true,
    isCore: false,
    dependencies: [],
    installedAt: '2026-09-28 15:00',
    updatedAt: '2026-10-04 18:00',
    status: 'healthy',
    author: 'Mecânica Eloizio / São Gonçalo',
    changelog: ['Orçamentos assistidos com análise de fotos de sintomas'],
    features: ['Reforma e conserto', 'Venda de máquinas e peças', 'Atendimento regional RJ'],
  },
  {
    id: 'mod_dne',
    slug: 'carteirinha_estudantil_dne',
    name: 'Carteirinha Estudantil Oficial DNE (Lei Federal 12.933/13)',
    description: 'Documento Nacional do Estudante digital com QR Code e validade para meia-entrada em todo o Brasil.',
    version: '2.0.1',
    category: 'academic',
    enabled: true,
    isCore: false,
    dependencies: ['mod_cursos'],
    installedAt: '2026-09-18 16:00',
    updatedAt: '2026-09-29 16:30',
    status: 'healthy',
    author: 'Diretoria de Identificação Estudantil',
    changelog: ['QR Code criptográfico padrão nacional adicionado'],
    features: ['Meia-entrada nacional', 'Download em alta resolução', 'Validação criptográfica'],
  },
  {
    id: 'mod_cli_terminal',
    slug: 'admin_cli_terminal',
    name: 'Console de Comandos & Terminal Administrativo CLI',
    description: 'Interface de linha de comando para executar manutenções, auditorias, migrações e diagnósticos.',
    version: '1.2.0',
    category: 'core',
    enabled: true,
    isCore: true,
    dependencies: ['mod_core'],
    installedAt: '2026-10-05 14:00',
    updatedAt: '2026-10-05 15:00',
    status: 'healthy',
    author: 'DevOps & Arquitetura',
    changelog: ['Terminal interativo adicionado com comandos de segurança, financeiro e módulos'],
    features: ['Comandos de auditoria', 'Gestão de módulos via CLI', 'Reconciliação financeira via comando'],
  },
];

export const DEFAULT_SECURITY_REPORT: SecurityAuditReport = {
  lastAuditAt: '2026-10-05 15:10',
  overallScore: 98,
  status: 'secure',
  totalChecks: 16,
  passedChecks: 16,
  categories: {
    authentication: {
      score: 100,
      passed: true,
      checks: [
        { name: 'Proteção contra Força Bruta (Lockout)', status: 'passed', detail: 'Bloqueio automático após 5 tentativas consecutivas com temporizador de segurança.' },
        { name: 'Validação e Sanitização de Credenciais', status: 'passed', detail: 'Filtro contra injeção SQL, normalização de e-mails e validação de tamanho mínimo.' },
        { name: 'Controle de Acesso Baseado em Funções (RBAC)', status: 'passed', detail: 'Separação estrita entre Aluno, Professor e Administrador Geral.' },
        { name: 'Confirmação 2FA para Operações Críticas', status: 'passed', detail: 'PIN de segurança requerido para operações sensíveis no Painel de Administração.' },
      ],
    },
    financial: {
      score: 96,
      passed: true,
      checks: [
        { name: 'Assinatura HMAC dos Webhooks do Mercado Pago', status: 'passed', detail: 'Assinatura validada com segredo criptográfico antes do processamento.' },
        { name: 'Chaves Idempotentes Anti-Duplicação', status: 'passed', detail: 'Geração de identificador único por pedido prevenindo cobranças duplicadas.' },
        { name: 'Validação de Valores e Limites Máximos', status: 'passed', detail: 'Bloqueio de transações negativas ou superiores ao teto de segurança cadastrado.' },
        { name: 'Auditoria e Conciliação Contábil Automática', status: 'passed', detail: 'Registro imutável de todas as transações PIX, Cartão e Boleto.' },
      ],
    },
    ai_guardrails: {
      score: 98,
      passed: true,
      checks: [
        { name: 'Proteção contra Injeção de Prompt (Jailbreak)', status: 'passed', detail: 'Filtro sanitizador de instruções adversárias bloqueia tentativas de bypass do sistema.' },
        { name: 'Proteção de Segredos & Chaves API', status: 'passed', detail: 'A IA está explicitamente instruída a jamais expor tokens, chaves internas ou senhas.' },
        { name: 'Privacidade LGPD de Dados Pessoais', status: 'passed', detail: 'Bloqueio de vazamento de CPF completo, números de cartão e dados sensíveis de alunos.' },
        { name: 'Aderência às Diretrizes Institucionais', status: 'passed', detail: 'Respostas alinhadas aos pilares do Grupo Eloizio (Cursos, Contabilidade e Mecânica).' },
      ],
    },
    data_protection: {
      score: 98,
      passed: true,
      checks: [
        { name: 'Criptografia SHA-256 dos Certificados', status: 'passed', detail: 'Hash criptográfico único impresso na frente e verso com validação pública.' },
        { name: 'Cofre de Tokens com Mascaramento', status: 'passed', detail: 'Visualização sob demanda de chaves com auditoria de visualização.' },
        { name: 'Backup e Snapshots Criptografados', status: 'passed', detail: 'Restauração atômica do banco de dados e estado com hash de integridade.' },
        { name: 'Isolamento de Ambiente Sandbox/Produção', status: 'passed', detail: 'Cartões e chaves de teste não interferem no faturamento de produção.' },
      ],
    },
  },
};

export async function computeSHA256Hash(text: string): Promise<string> {
  try {
    const encoder = new TextEncoder();
    const data = encoder.encode(text);
    const hashBuffer = await crypto.subtle.digest('SHA-256', data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
  } catch {
    // fallback hash
    let hash = 0;
    for (let i = 0; i < text.length; i++) {
      hash = ((hash << 5) - hash) + text.charCodeAt(i);
      hash |= 0;
    }
    return 'fallback_' + Math.abs(hash).toString(16);
  }
}
